networks:
  net111:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.241.111.0/24
          gateway: 172.241.111.254

services:
  morbilidade:
    build:
      context: .
      dockerfile: dockerfiles/php/Dockerfile
    image: application
    container_name: applicationMorbilidade
    tty: true
    ports:
      - "9000:9000"
    volumes:
      - ./var/www:/var/www
    networks:
      net111:
        ipv4_address: 172.241.111.5

  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "43306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: yourdb
      MYSQL_PASSWORD: password
    networks:
      net111:
        ipv4_address: 172.241.111.6

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      net111:
        ipv4_address: 172.241.111.7

volumes:
  db_data:
